name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH and run command on server
      env:
        key: ${{ secrets.AWS_POM }}
      run: |
        echo "$key" > key
        chmod 600 keyfile
        mkdir -p ~/.ssh
        cp known_hosts ~/.ssh/known_hosts
        ssh -t -i key ubuntu@ec2-65-1-248-170.ap-south-1.compute.amazonaws.com "source script.sh"
