name: Deploy

on:
  push:
    branches:
      - master 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH and deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > keyfile
        chmod 600 keyfile
        mkdir -p ~/.ssh
        ssh-keyscan ec2-15-206-195-92.ap-south-1.compute.amazonaws.com >> known_hosts
        cp known_hosts ~/.ssh/known_hosts
        ssh -t -i keyfile ubuntu@ec2-15-206-195-92.ap-south-1.compute.amazonaws.com "sudo bash ~/deploy.sh"
