name: Deploy

on:
  push:
    branches:
      - master 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH and deploy
      run: |
        cp key ~/keyfile
        chmod 600 ~/keyfile
        mkdir ~/.ssh
        cp known_hosts ~/.ssh/known_hosts
        ssh -i ~/keyfile ubuntu@ec2-15-206-195-92.ap-south-1.compute.amazonaws.com
